package shamir

import (
	"testing"
)

func TestCombineReconstructsSecret(t *testing.T) {
	// These shares were generated by the frontend shamir.js share("hello", 2, 2)
	// We can verify by creating a known test case.
	// For unit testing: split a known hex, combine, verify.

	// Manual GF(256) test: secret byte = 0x48 ('H' in ASCII)
	// With share IDs 1 and 2, and coefficient c1:
	// P(1) = 0x48 XOR mul(c1, 1) = s XOR c1
	// P(2) = 0x48 XOR mul(c1, 2)
	// Combine should give back 0x48

	// Use the frontend's share format to ensure compatibility.
	// We test the math directly: combine(["1-xx","2-yy"]) should reconstruct.

	// Simple round-trip test using known GF(256) math:
	// Secret = "0048" (H), c1 = 0x37
	// P(1) = 0x48 XOR 0x37 = 0x7f → share "1-7f"
	// P(2) = 0x48 XOR mul(0x37, 2) = 0x48 XOR 0x6e = 0x26 → share "2-26"
	result, err := Combine("1-7f", "2-26")
	if err != nil {
		t.Fatalf("Combine failed: %v", err)
	}
	if result != "48" {
		t.Errorf("Expected '48', got %q", result)
	}
}

func TestCombineMultipleBytes(t *testing.T) {
	// Secret: "Hi" = 0x48 0x69
	// c1_0 = 0x37, c1_1 = 0x1a
	// P_0(1) = 0x48^0x37=0x7f, P_0(2) = 0x48^mul(0x37,2)=0x48^0x6e=0x26
	// P_1(1) = 0x69^0x1a=0x73, P_1(2) = 0x69^mul(0x1a,2)=0x69^0x34=0x5d
	result, err := Combine("1-7f73", "2-265d")
	if err != nil {
		t.Fatalf("Combine failed: %v", err)
	}
	if result != "4869" {
		t.Errorf("Expected '4869', got %q", result)
	}
}

func TestHex2Str(t *testing.T) {
	// "Hi" → hex2str needs chars encoded as 4-hex-char blocks, reversed
	// 'H' = 0x0048, 'i' = 0x0069
	// str2hex("Hi") = "0069" + "0048" = "00690048" (prepended, so reversed)
	result := Hex2Str("00690048")
	if result != "Hi" {
		t.Errorf("Expected 'Hi', got %q", result)
	}
}

func TestHex2StrSingleChar(t *testing.T) {
	result := Hex2Str("0041")
	if result != "A" {
		t.Errorf("Expected 'A', got %q", result)
	}
}

func TestCombineInvalidFormat(t *testing.T) {
	_, err := Combine("invalid", "2-abcd")
	if err == nil {
		t.Error("Expected error for invalid share format")
	}
}

func TestCombineLengthMismatch(t *testing.T) {
	_, err := Combine("1-abcd", "2-ab")
	if err == nil {
		t.Error("Expected error for length mismatch")
	}
}
