sonar.projectKey=pyxcloud-cli
sonar.projectName=PyxCloud CLI
sonar.projectVersion=0.0.1
sonar.sources=.
sonar.language=go
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*_test.go,vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
