package passocli

import (
	"bytes"
	"context"
	"encoding/json"
	"net/http"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/pyxcloud/pyxcloud-cli/internal/passoauth"
)

type catalogDocument struct {
	SchemaVersion int              `json:"schemaVersion"`
	Commands      []catalogCommand `json:"commands"`
}

type catalogCommand struct {
	Path             string        `json:"path"`
	Use              string        `json:"use"`
	ShortDescription string        `json:"shortDescription"`
	Hidden           bool          `json:"hidden"`
	Flags            []catalogFlag `json:"flags"`
}

type catalogFlag struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	Required bool   `json:"required"`
}

type catalogTripwireStore struct{}

func (catalogTripwireStore) Load(string) (passoauth.Token, error) {
	panic("catalog loaded credentials")
}
func (catalogTripwireStore) Save(string, passoauth.Token) error { panic("catalog saved credentials") }
func (catalogTripwireStore) Delete(string) error                { panic("catalog deleted credentials") }

type catalogTripwireTransport struct{}

func (catalogTripwireTransport) RoundTrip(*http.Request) (*http.Response, error) {
	panic("catalog used HTTP")
}

func readCommandCatalog(t *testing.T, args ...string) (catalogDocument, []byte) {
	t.Helper()
	var out, errOut bytes.Buffer
	cmd := New(Options{
		Out:        &out,
		Err:        &errOut,
		Store:      catalogTripwireStore{},
		HTTPClient: &http.Client{Transport: catalogTripwireTransport{}},
	})
	cmd.SetArgs(args)
	if err := cmd.ExecuteContext(context.Background()); err != nil {
		t.Fatalf("commands failed: %v stderr=%q", err, errOut.String())
	}
	var got catalogDocument
	if err := json.Unmarshal(out.Bytes(), &got); err != nil {
		t.Fatalf("invalid catalog JSON %q: %v", out.String(), err)
	}
	return got, append([]byte(nil), out.Bytes()...)
}

func findCatalogCommand(doc catalogDocument, path string) (catalogCommand, bool) {
	for _, command := range doc.Commands {
		if command.Path == path {
			return command, true
		}
	}
	return catalogCommand{}, false
}

func findCatalogFlag(command catalogCommand, name string) (catalogFlag, bool) {
	for _, flag := range command.Flags {
		if flag.Name == name {
			return flag, true
		}
	}
	return catalogFlag{}, false
}

func TestCommandsJSONCatalogIsStableAndListsVisibleWorkflowCommands(t *testing.T) {
	first, firstBytes := readCommandCatalog(t, "commands", "--json")
	_, secondBytes := readCommandCatalog(t, "commands", "--json")
	if !bytes.Equal(firstBytes, secondBytes) {
		t.Fatalf("catalog output changed between identical reads:\n%s\n%s", firstBytes, secondBytes)
	}
	if first.SchemaVersion != 1 {
		t.Fatalf("schemaVersion=%d", first.SchemaVersion)
	}
	paths := make([]string, len(first.Commands))
	for i, command := range first.Commands {
		paths[i] = command.Path
		if command.Hidden || command.Path == "help" || command.ShortDescription == "" {
			t.Fatalf("invalid visible command metadata: %#v", command)
		}
	}
	if !sort.StringsAreSorted(paths) {
		t.Fatalf("command paths are not sorted: %#v", paths)
	}
	for _, want := range []string{"login", "status", "run", "projects", "connect", "discover", "docs", "define", "design", "compare", "freeze", "secure", "seal", "deploy", "monitor"} {
		if _, ok := findCatalogCommand(first, want); !ok {
			t.Errorf("catalog omitted command/group %q", want)
		}
	}
	run, ok := findCatalogCommand(first, "run")
	if !ok || !strings.Contains(run.Use, "run") {
		t.Fatalf("run usage metadata missing: %#v", run)
	}
	to, ok := findCatalogFlag(run, "to")
	if !ok || !to.Required || to.Type != "string" {
		t.Fatalf("run --to metadata=%#v found=%v", to, ok)
	}
	status, ok := findCatalogCommand(first, "status")
	if !ok {
		t.Fatal("status missing")
	}
	for _, name := range []string{"json", "project", "profile"} {
		if _, ok := findCatalogFlag(status, name); !ok {
			t.Errorf("status omitted inherited --%s flag", name)
		}
	}
	for _, command := range first.Commands {
		for _, flag := range command.Flags {
			if flag.Name == "help" {
				t.Fatalf("autogenerated help flag leaked into catalog for %s", command.Path)
			}
		}
	}
}

func TestCommandsJSONCatalogIncludesRequiredInputAndOmitsGetInput(t *testing.T) {
	doc, _ := readCommandCatalog(t, "commands", "--json")
	create, ok := findCatalogCommand(doc, "projects create")
	if !ok {
		t.Fatal("projects create missing")
	}
	input, ok := findCatalogFlag(create, "input")
	if !ok || !input.Required || input.Type != "string" {
		t.Fatalf("projects create --input metadata=%#v found=%v", input, ok)
	}
	get, ok := findCatalogCommand(doc, "projects get")
	if !ok {
		t.Fatal("projects get missing")
	}
	if _, ok := findCatalogFlag(get, "input"); ok {
		t.Fatal("GET command exposed an --input flag")
	}
	encoded, err := json.Marshal(doc)
	if err != nil {
		t.Fatal(err)
	}
	for _, secretOrDefault := range []string{"sandbox", ".passo/run.json", "ephemeral", "credentials"} {
		if strings.Contains(string(encoded), secretOrDefault) {
			t.Fatalf("catalog exposed a default or credential term %q", secretOrDefault)
		}
	}
}

func TestCommandsCatalogDoesNotInitializeRuntimeOrCallHTTP(t *testing.T) {
	doc, _ := readCommandCatalog(t, "--profile", "not-a-profile", "--ledger", "/missing/catalog-ledger.json", "commands", "--json")
	if doc.SchemaVersion != 1 {
		t.Fatalf("catalog did not run independently of invalid runtime config: %#v", doc)
	}
}

func TestCommandsCatalogKeepsHumanOutputConciseAndUnknownFlagsCobraOwned(t *testing.T) {
	var out, errOut bytes.Buffer
	cmd := New(Options{Out: &out, Err: &errOut, Store: catalogTripwireStore{}})
	cmd.SetArgs([]string{"commands"})
	if err := cmd.ExecuteContext(context.Background()); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "login") || !strings.Contains(out.String(), "projects create") || strings.Count(out.String(), "\n") > 100 {
		t.Fatalf("human catalog output was not concise: %q", out.String())
	}
	cmd = New(Options{Out: &out, Err: &errOut, Store: catalogTripwireStore{}, Now: time.Now})
	cmd.SetArgs([]string{"commands", "--unknown"})
	err := cmd.ExecuteContext(context.Background())
	if err == nil || !strings.Contains(err.Error(), "unknown flag") {
		t.Fatalf("expected ordinary Cobra unknown-flag error, got %v", err)
	}
}
