// Code generated by cmd/contractgen; DO NOT EDIT.
package passocontract

import "encoding/json"

type ApiError struct {
	Error   *string `json:"error"`
	Message *string `json:"message"`
}

type ArchitectureFacts struct {
	Components        []string `json:"components"`
	Environments      []string `json:"environments"`
	MissingSecretKeys []string `json:"missingSecretKeys"`
}

type Blocker struct {
	Code           *string `json:"code"`
	Message        *string `json:"message"`
	RequiredAction *string `json:"requiredAction"`
}

type BoardAgent struct {
	Id     *string `json:"id"`
	Label  *string `json:"label"`
	Status *string `json:"status"`
}

type BoardFacts struct {
	Agents          []BoardAgent     `json:"agents"`
	FreezeAvailable *bool            `json:"freezeAvailable"`
	TasksByState    map[string]int64 `json:"tasksByState"`
}

type Capability struct {
	Allowed *bool   `json:"allowed"`
	Key     *string `json:"key"`
	Reason  *string `json:"reason"`
}

type CloudFacts struct {
	Currency     *string `json:"currency"`
	MonthlyMinor *int64  `json:"monthlyMinor"`
	Provider     *string `json:"provider"`
	Region       *string `json:"region"`
	SnapshotDate *string `json:"snapshotDate"`
}

type DeploymentFacts struct {
	BuildJobState            *string               `json:"buildJobState"`
	LatestRun                *DeploymentRunSummary `json:"latestRun"`
	PreviousReleaseStillLive *bool                 `json:"previousReleaseStillLive"`
}

type DeploymentRunSummary struct {
	Env       *string          `json:"env"`
	ErrorCode *string          `json:"errorCode"`
	RunId     *string          `json:"runId"`
	State     *string          `json:"state"`
	Steps     []DeploymentStep `json:"steps"`
}

type DeploymentStep struct {
	Key     *string `json:"key"`
	Message *string `json:"message"`
	State   *string `json:"state"`
}

type Facts struct {
	Architecture *ArchitectureFacts `json:"architecture"`
	Board        *BoardFacts        `json:"board"`
	Cloud        *CloudFacts        `json:"cloud"`
	Deployment   *DeploymentFacts   `json:"deployment"`
	Gate         *GateFacts         `json:"gate"`
	Live         *LiveFacts         `json:"live"`
	Release      *ReleaseFacts      `json:"release"`
}

type Freshness struct {
	AsOf          *string `json:"asOf"`
	SourceVersion *int64  `json:"sourceVersion"`
}

type GateBlockerClass struct {
	Class   *string  `json:"class"`
	Count   *int64   `json:"count"`
	TaskIds []string `json:"taskIds"`
}

type GateFacts struct {
	BlockersByClass  []GateBlockerClass   `json:"blockersByClass"`
	NotCheckedGaps   []string             `json:"notCheckedGaps"`
	Notes            []GateNote           `json:"notes"`
	PendingDecisions *int64               `json:"pendingDecisions"`
	ScanProgress     []ScanTargetProgress `json:"scanProgress"`
	Stale            *bool                `json:"stale"`
	Verdict          *string              `json:"verdict"`
}

type GateNote struct {
	Expired   *bool   `json:"expired"`
	ExpiresAt *string `json:"expiresAt"`
	FindingId *string `json:"findingId"`
	Note      *string `json:"note"`
}

type JourneyEnvelope struct {
	Blockers     []Blocker    `json:"blockers"`
	Capabilities []Capability `json:"capabilities"`
	Data         *JourneyRead `json:"data"`
	Freshness    *Freshness   `json:"freshness"`
	Version      *int64       `json:"version"`
}

type JourneyRead struct {
	Facts         *Facts          `json:"facts"`
	NeedsYou      []NeedsYouItem  `json:"needsYou"`
	PrimaryAction *PrimaryAction  `json:"primaryAction"`
	ProjectId     *int64          `json:"projectId"`
	Projection    json.RawMessage `json:"projection"`
	Stage         *string         `json:"stage"`
	SubState      *string         `json:"subState"`
	Version       *VersionRef     `json:"version"`
}

type LiveEnvironment struct {
	Health     *LiveHealth  `json:"health"`
	Kind       *string      `json:"kind"`
	Price      *LivePrice   `json:"price"`
	PriceLabel *string      `json:"priceLabel"`
	Url        *string      `json:"url"`
	Version    *LiveVersion `json:"version"`
}

type LiveFacts struct {
	Environments []LiveEnvironment `json:"environments"`
}

type LiveHealth struct {
	DownSince  *string `json:"downSince"`
	LatencyMs  *int64  `json:"latencyMs"`
	ObservedAt *string `json:"observedAt"`
	Status     *string `json:"status"`
}

type LivePrice struct {
	AlertLabel          *string       `json:"alertLabel"`
	AlertMinor          *int64        `json:"alertMinor"`
	AlertUpdatedAt      *string       `json:"alertUpdatedAt"`
	MonthToDateAsOf     *string       `json:"monthToDateAsOf"`
	MonthToDateCurrency *string       `json:"monthToDateCurrency"`
	MonthToDateLabel    *string       `json:"monthToDateLabel"`
	MonthToDateMinor    *int64        `json:"monthToDateMinor"`
	Monthly             *MonthlyPrice `json:"monthly"`
	SnapshotDate        *string       `json:"snapshotDate"`
	Sources             []string      `json:"sources"`
}

type LiveVersion struct {
	Commit     *string `json:"commit"`
	Label      *string `json:"label"`
	ReleasedAt *string `json:"releasedAt"`
}

type MonthlyPrice struct {
	Currency   *string `json:"currency"`
	FeeMinor   *int64  `json:"feeMinor"`
	InfraMinor *int64  `json:"infraMinor"`
	TotalMinor *int64  `json:"totalMinor"`
}

type NeedsYouItem struct {
	Href    *string `json:"href"`
	Kind    *string `json:"kind"`
	Message *string `json:"message"`
	Since   *string `json:"since"`
}

type PrimaryAction struct {
	Allowed *bool   `json:"allowed"`
	Href    *string `json:"href"`
	Key     *string `json:"key"`
	Label   *string `json:"label"`
	Reason  *string `json:"reason"`
}

type ReleaseFacts struct {
	Sealed       *bool   `json:"sealed"`
	State        *string `json:"state"`
	VersionLabel *string `json:"versionLabel"`
}

type ScanTargetProgress struct {
	Check  *string `json:"check"`
	Status *string `json:"status"`
	Target *string `json:"target"`
}

type VersionRef struct {
	Id       *string `json:"id"`
	Label    *string `json:"label"`
	LockedAt *string `json:"lockedAt"`
	Sequence *int64  `json:"sequence"`
}
